/**
 * Static validation of every builder's output shape against the official
 * Schema.org vocabulary (Google's `schema-dts`, generated from schema.org).
 * `npm run validate` (tsc --noEmit) fails if any shape is invalid.
 */
import type {
  WithContext, Product, Offer, Review, AggregateRating, Article, BlogPosting, NewsArticle,
  Recipe, VideoObject, ImageObject, Person, Organization, WebSite, WebPage, ProfilePage,
  BreadcrumbList, FAQPage, HowTo, CollectionPage, Event, LocalBusiness, JobPosting,
  SoftwareApplication, Course, Service,
  ItemList, Menu, MenuSection, MenuItem, RealEstateListing, Apartment,
  MusicGroup, MusicAlbum, MusicRecording, Dentist, Restaurant, MusicEvent,
} from 'schema-dts';

const C = 'https://schema.org' as const;

export const samples: Record<string, object> = {
  product: { '@context': C, '@type': 'Product', name: 'X', url: 'u', description: 'd', image: 'i', sku: 's',
    brand: { '@type': 'Organization', name: 'Acme' },
    offers: { '@type': 'Offer', url: 'u', priceCurrency: 'USD', price: '9', availability: 'https://schema.org/InStock' },
    aggregateRating: { '@type': 'AggregateRating', ratingValue: 4.8, reviewCount: 64, bestRating: 5 },
    additionalProperty: [{ '@type': 'PropertyValue', name: 'Format', value: 'WAV' }],
    review: [{ '@type': 'Review', reviewRating: { '@type': 'Rating', ratingValue: 5, bestRating: 5 }, author: { '@type': 'Person', name: 'Jane' }, reviewBody: 'b', datePublished: '2026-01-01' }] } satisfies WithContext<Product>,
  offer: { '@context': C, '@type': 'Offer', url: 'u', price: '9', priceCurrency: 'USD', availability: 'https://schema.org/InStock', priceValidUntil: '2026-12-31' } satisfies WithContext<Offer>,
  review: { '@context': C, '@type': 'Review', reviewRating: { '@type': 'Rating', ratingValue: 5, bestRating: 5 }, author: { '@type': 'Person', name: 'B' }, reviewBody: 'b', datePublished: '2026-01-01' } satisfies WithContext<Review>,
  aggregateRating: { '@context': C, '@type': 'AggregateRating', ratingValue: 4.5, reviewCount: 10, bestRating: 5 } satisfies WithContext<AggregateRating>,
  article: { '@context': C, '@type': 'Article', headline: 'H', url: 'u', description: 'd', image: 'i', datePublished: '2026-01-01', dateModified: '2026-01-02', author: { '@type': 'Person', name: 'J' }, publisher: { '@type': 'Organization', name: 'O' }, articleSection: 'Tech', keywords: 'a, b' } satisfies WithContext<Article>,
  blogPosting: { '@context': C, '@type': 'BlogPosting', headline: 'H', url: 'u' } satisfies WithContext<BlogPosting>,
  newsArticle: { '@context': C, '@type': 'NewsArticle', headline: 'H', url: 'u' } satisfies WithContext<NewsArticle>,
  recipe: { '@context': C, '@type': 'Recipe', name: 'R', image: 'i', author: { '@type': 'Person', name: 'J' }, description: 'd', datePublished: '2026-01-01', prepTime: 'PT15M', cookTime: 'PT30M', totalTime: 'PT45M', recipeYield: '4', recipeIngredient: ['x'], recipeInstructions: [{ '@type': 'HowToStep', text: 'mix' }] } satisfies WithContext<Recipe>,
  videoObject: { '@context': C, '@type': 'VideoObject', name: 'V', description: 'd', thumbnailUrl: 't', uploadDate: '2026-01-01', contentUrl: 'c', embedUrl: 'e', duration: 'PT2M' } satisfies WithContext<VideoObject>,
  imageObject: { '@context': C, '@type': 'ImageObject', url: 'i', width: { '@type': 'QuantitativeValue', value: 1200 }, height: { '@type': 'QuantitativeValue', value: 630 }, caption: 'c' } satisfies WithContext<ImageObject>,
  person: { '@context': C, '@type': 'Person', name: 'J', url: 'u', image: 'i', jobTitle: 'D', description: 'b', email: 'e@x', worksFor: { '@type': 'Organization', name: 'O' }, sameAs: ['s'] } satisfies WithContext<Person>,
  organization: { '@context': C, '@type': 'Organization', name: 'O', url: 'u', logo: 'l', description: 'd', sameAs: ['s'] } satisfies WithContext<Organization>,
  webSite: { '@context': C, '@type': 'WebSite', name: 'W', url: 'u', potentialAction: { '@type': 'SearchAction', target: { '@type': 'EntryPoint', urlTemplate: 'u?q={search_term_string}' }, 'query-input': 'required name=search_term_string' } } as WithContext<WebSite>, // `query-input` is Google's sitelinks-searchbox extension (official), not in core schema.org / schema-dts
  webPage: { '@context': C, '@type': 'WebPage', name: 'P', url: 'u', description: 'd', primaryImageOfPage: { '@type': 'ImageObject', url: 'i' }, datePublished: '2026-01-01', dateModified: '2026-01-02' } satisfies WithContext<WebPage>,
  profilePage: { '@context': C, '@type': 'ProfilePage', url: 'u', dateCreated: '2026-01-01', dateModified: '2026-01-02', mainEntity: { '@type': 'Person', name: 'J' } } satisfies WithContext<ProfilePage>,
  breadcrumb: { '@context': C, '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'u' }, { '@type': 'ListItem', position: 2, name: 'Now' }] } satisfies WithContext<BreadcrumbList>,
  faq: { '@context': C, '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Q?', acceptedAnswer: { '@type': 'Answer', text: 'A' } }] } satisfies WithContext<FAQPage>,
  howTo: { '@context': C, '@type': 'HowTo', name: 'H', description: 'd', totalTime: 'PT5M', step: [{ '@type': 'HowToStep', position: 1, name: 'S', text: 't', url: 'u', image: 'i' }] } satisfies WithContext<HowTo>,
  collectionPage: { '@context': C, '@type': 'CollectionPage', name: 'C', url: 'u', description: 'd', provider: { '@type': 'Organization', name: 'O' } } satisfies WithContext<CollectionPage>,
  event: { '@context': C, '@type': 'Event', name: 'E', startDate: '2026-06-01T18:00:00Z', url: 'u', endDate: '2026-06-01T20:00:00Z', description: 'd', image: 'i', location: { '@type': 'Place', name: 'V' }, organizer: { '@type': 'Organization', name: 'O' } } satisfies WithContext<Event>,
  localBusiness: { '@context': C, '@type': 'LocalBusiness', name: 'B', url: 'u', image: 'i', telephone: '+1', priceRange: '$$', address: { '@type': 'PostalAddress', streetAddress: '123 Main', addressLocality: 'Town' }, geo: { '@type': 'GeoCoordinates', latitude: 1, longitude: 2 }, aggregateRating: { '@type': 'AggregateRating', ratingValue: 4, reviewCount: 5, bestRating: 5 } } satisfies WithContext<LocalBusiness>,
  jobPosting: { '@context': C, '@type': 'JobPosting', title: 'E', description: 'd', datePosted: '2026-06-01', hiringOrganization: { '@type': 'Organization', name: 'A' }, url: 'u', validThrough: '2026-12-31', employmentType: 'FULL_TIME', jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressLocality: 'Remote' } }, jobLocationType: 'TELECOMMUTE', baseSalary: { '@type': 'MonetaryAmount', currency: 'USD', value: { '@type': 'QuantitativeValue', value: '120000', unitText: 'YEAR' } } } satisfies WithContext<JobPosting>,
  softwareApplication: { '@context': C, '@type': 'SoftwareApplication', name: 'S', url: 'u', description: 'd', operatingSystem: 'macOS', applicationCategory: 'DeveloperApplication', offers: { '@type': 'Offer', price: '49', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: 4, reviewCount: 5, bestRating: 5 } } satisfies WithContext<SoftwareApplication>,
  course: { '@context': C, '@type': 'Course', name: 'C', description: 'd', url: 'u', provider: { '@type': 'Organization', name: 'O' } } satisfies WithContext<Course>,
  service: { '@context': C, '@type': 'Service', name: 'S', description: 'd', serviceType: 'T', areaServed: 'US', url: 'u', provider: { '@type': 'Organization', name: 'O' } } satisfies WithContext<Service>,

  /* ── Directory / sector builders ── */
  localBusinessDentist: { '@context': C, '@type': 'Dentist', name: 'Smile', url: 'u', telephone: '+44', email: 'a@b.c',
    address: { '@type': 'PostalAddress', streetAddress: '1 High St', addressLocality: 'Bristol', postalCode: 'BS1 5JA' },
    geo: { '@type': 'GeoCoordinates', latitude: 1, longitude: 2 },
    openingHoursSpecification: [
      { '@type': 'OpeningHoursSpecification', dayOfWeek: ['Monday', 'Tuesday'], opens: '09:00', closes: '17:30' },
      { '@type': 'OpeningHoursSpecification', dayOfWeek: ['Sunday'], opens: '00:00', closes: '00:00' },
    ] } satisfies WithContext<Dentist>,
  localBusinessRestaurant: { '@context': C, '@type': 'Restaurant', name: 'T', servesCuisine: ['Italian'],
    hasMenu: 'https://x/menu', acceptsReservations: true } satisfies WithContext<Restaurant>,
  itemList: { '@context': C, '@type': 'ItemList', name: 'L', url: 'u', itemListOrder: 'ItemListOrderAscending', numberOfItems: 2,
    itemListElement: [
      { '@type': 'ListItem', position: 1, url: 'https://x/a' },
      { '@type': 'ListItem', position: 2, item: { '@type': 'Dentist', name: 'B' } },
    ] } satisfies WithContext<ItemList>,
  menu: { '@context': C, '@type': 'Menu', name: 'Dinner', url: 'u', description: 'd',
    hasMenuSection: [{ '@type': 'MenuSection', name: 'Small plates',
      hasMenuItem: [{ '@type': 'MenuItem', name: 'P', offers: { '@type': 'Offer', price: '6.5', priceCurrency: 'GBP', availability: 'https://schema.org/InStock' },
        suitableForDiet: 'https://schema.org/VeganDiet',
        nutrition: { '@type': 'NutritionInformation', calories: '120 calories' } }] }] } satisfies WithContext<Menu>,
  menuSection: { '@context': C, '@type': 'MenuSection', name: 'S', description: 'd',
    hasMenuItem: [{ '@type': 'MenuItem', name: 'I' }] } satisfies WithContext<MenuSection>,
  menuItem: { '@context': C, '@type': 'MenuItem', name: 'I', description: 'd',
    offers: { '@type': 'Offer', price: '3', priceCurrency: 'GBP', availability: 'https://schema.org/InStock' } } satisfies WithContext<MenuItem>,
  realEstateListing: { '@context': C, '@type': 'RealEstateListing', name: 'Flat', url: 'u', description: 'd', image: 'i',
    datePosted: '2026-08-01',
    offers: { '@type': 'Offer', url: 'u', price: '1450', priceCurrency: 'GBP', availability: 'https://schema.org/InStock' },
    provider: { '@type': 'RealEstateAgent', name: 'Acme' },
    about: { '@type': 'Apartment', numberOfBedrooms: 2, numberOfBathroomsTotal: 1,
      address: { '@type': 'PostalAddress', addressLocality: 'Bristol' },
      geo: { '@type': 'GeoCoordinates', latitude: 1, longitude: 2 },
      floorSize: { '@type': 'QuantitativeValue', value: 68, unitCode: 'MTK' },
      amenityFeature: [{ '@type': 'LocationFeatureSpecification', name: 'Parking', value: true }] } } satisfies WithContext<RealEstateListing>,
  accommodation: { '@context': C, '@type': 'Apartment', name: 'A', numberOfBedrooms: 2, numberOfRooms: 3,
    yearBuilt: 1998,
    floorSize: { '@type': 'QuantitativeValue', value: 68, unitCode: 'MTK' },
    address: { '@type': 'PostalAddress', addressLocality: 'Bristol' } } satisfies WithContext<Apartment>,
  musicGroup: { '@context': C, '@type': 'MusicGroup', name: 'S', url: 'u', image: 'i', description: 'd', genre: 'Ambient',
    sameAs: ['https://spindrift.bandcamp.com'], member: [{ '@type': 'Person', name: 'Jane' }],
    foundingDate: '2019-01-01', foundingLocation: { '@type': 'Place', name: 'Bristol' },
    album: [{ '@type': 'MusicAlbum', name: 'Tidal', albumProductionType: 'https://schema.org/DJMixAlbum',
      track: [{ '@type': 'MusicRecording', name: 'Drift', duration: 'PT4M33S' }] }] } satisfies WithContext<MusicGroup>,
  musicAlbum: { '@context': C, '@type': 'MusicAlbum', name: 'T', url: 'u', image: 'i', datePublished: '2026-01-01',
    genre: 'Ambient', numTracks: 8, byArtist: { '@type': 'MusicGroup', name: 'S' },
    offers: { '@type': 'Offer', url: 'u', price: '9', priceCurrency: 'GBP', availability: 'https://schema.org/InStock' } } satisfies WithContext<MusicAlbum>,
  musicRecording: { '@context': C, '@type': 'MusicRecording', name: 'D', url: 'u', duration: 'PT4M33S',
    byArtist: { '@type': 'MusicGroup', name: 'S' }, inAlbum: { '@type': 'MusicAlbum', name: 'T' },
    audio: { '@type': 'AudioObject', contentUrl: 'https://x/a.mp3' }, isrcCode: 'GB-XXX-26-00001' } satisfies WithContext<MusicRecording>,
  musicEvent: { '@context': C, '@type': 'MusicEvent', name: 'Gig', startDate: '2026-09-01T20:00:00Z',
    performer: [{ '@type': 'MusicGroup', name: 'S' }],
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    offers: { '@type': 'Offer', price: '15', priceCurrency: 'GBP', availability: 'https://schema.org/InStock' } } satisfies WithContext<MusicEvent>,
};
void samples;
